name: hola mundo

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "*/5 * * * *" # Se ejcuta cada 5 minutos
  #push:
  #  branches:
  #    - main

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Muestra mensaje hola mundo
        run: echo "hola mundo, Hector"
      
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Listar los archivos del repositorio
        run: |
          echo "El repositorio ${{ github.repository }} contiene los siguiente archivos:"
          tree
